### ISSUE TITLE
Julia 1.10 fails on GPUs

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaAtmos.jl#2477] opened 2024-01-04 00:21 UTC
Using Julia 1.10 fails on GPUs with error:
```
ERROR: InvalidIRError: compiling MethodInstance for ClimaCore.DataLayouts.knl_copyto!(::ClimaCore.DataLayouts.IJFH{…}, ::Base.Broadcast.Broadcasted{…}) resulted in invalid LLVM IR
Reason: unsupported call to an unknown function (call to julia.new_gc_frame)
Stacktrace:
 [1] surface_conditions (repeats 2 times)
   @ ~/SurfaceFluxes.jl/src/SurfaceFluxes.jl:283
 [2] surface_state_to_conditions
   @ ~/ClimaAtmos.jl/src/surface_conditions/surface_conditions.jl:353
 [3] surface_state_to_conditions
   @ ~/ClimaAtmos.jl/src/surface_conditions/surface_conditions.jl:158
 [4] _broadcast_getindex_evalf
   @ ./broadcast.jl:709
 [5] _broadcast_getindex
   @ ./broadcast.jl:682
 [6] getindex
   @ ./broadcast.jl:636
 [7] knl_copyto!
   @ ~/.julia/packages/ClimaCore/WtnDS/src/DataLayouts/cuda.jl:56
Reason: unsupported call to an unknown function (call to julia.get_gc_frame_slot)
Stacktrace:
 [1] surface_conditions (repeats 2 times)
   @ ~/SurfaceFluxes.jl/src/SurfaceFluxes.jl:283
 [2] surface_state_to_conditions
   @ ~/ClimaAtmos.jl/src/surface_conditions/surface_conditions.jl:353
 [3] surface_state_to_conditions
   @ ~/ClimaAtmos.jl/src/surface_conditions/surface_conditions.jl:158
 [4] _broadcast_getindex_evalf
   @ ./broadcast.jl:709
 [5] _broadcast_getindex
   @ ./broadcast.jl:682
 [6] getindex
   @ ./broadcast.jl:636
 [7] knl_copyto!
   @ ~/.julia/packages/ClimaCore/WtnDS/src/DataLayouts/cuda.jl:56
Reason: unsupported call to an unknown function (call to julia.push_gc_frame)
Stacktrace:
 [1] surface_conditions (repeats 2 times)
   @ ~/SurfaceFluxes.jl/src/SurfaceFluxes.jl:283
 [2] surface_state_to_conditions
   @ ~/ClimaAtmos.jl/src/surface_conditions/surface_conditions.jl:353
 [3] surface_state_to_conditions
   @ ~/ClimaAtmos.jl/src/surface_conditions/surface_conditions.jl:158
 [4] _broadcast_getindex_evalf
   @ ./broadcast.jl:709
 [5] _broadcast_getindex
   @ ./broadcast.jl:682
 [6] getindex
   @ ./broadcast.jl:636
 [7] knl_copyto!
   @ ~/.julia/packages/ClimaCore/WtnDS/src/DataLayouts/cuda.jl:56
Reason: unsupported call to an unknown function (call to julia.pop_gc_frame)
Stacktrace:
 [1] surface_conditions (repeats 2 times)
   @ ~/SurfaceFluxes.jl/src/SurfaceFluxes.jl:283
 [2] surface_state_to_conditions
   @ ~/ClimaAtmos.jl/src/surface_conditions/surface_conditions.jl:353
 [3] surface_state_to_conditions
   @ ~/ClimaAtmos.jl/src/surface_conditions/surface_conditions.jl:158
 [4] _broadcast_getindex_evalf
   @ ./broadcast.jl:709
 [5] _broadcast_getindex
   @ ./broadcast.jl:682
 [6] getindex
   @ ./broadcast.jl:636
 [7] knl_copyto!
   @ ~/.julia/packages/ClimaCore/WtnDS/src/DataLayouts/cuda.jl:56
Hint: catch this exception as `err` and call `code_typed(err; interactive = true)` to introspect the erronous code with Cthulhu.jl
Stacktrace:
  [1] check_ir(job::GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams}, args::LLVM.Module)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/validation.jl:147
  [2] macro expansion
    @ ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:440 [inlined]
  [3] macro expansion
    @ ~/.julia/packages/TimerOutputs/RsWnF/src/TimerOutput.jl:253 [inlined]
  [4] macro expansion
    @ ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:439 [inlined]
  [5] emit_llvm(job::GPUCompiler.CompilerJob; libraries::Bool, toplevel::Bool, optimize::Bool, cleanup::Bool, only_entry::Bool, validate::Bool)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/utils.jl:92
  [6] emit_llvm
    @ ~/.julia/packages/GPUCompiler/U36Ed/src/utils.jl:86 [inlined]
  [7] 
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:129
  [8] codegen
    @ ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:110 [inlined]
  [9] 
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:106
 [10] compile
    @ ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:98 [inlined]
 [11] #1075
    @ ~/.julia/packages/CUDA/YIj5X/src/compiler/compilation.jl:247 [inlined]
 [12] JuliaContext(f::CUDA.var"#1075#1077"{GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams}})
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/driver.jl:47
 [13] compile(job::GPUCompiler.CompilerJob)
    @ CUDA ~/.julia/packages/CUDA/YIj5X/src/compiler/compilation.jl:246
 [14] actual_compilation(cache::Dict{…}, src::Core.MethodInstance, world::UInt64, cfg::GPUCompiler.CompilerConfig{…}, compiler::typeof(CUDA.compile), linker::typeof(CUDA.link))
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/execution.jl:125
 [15] cached_compilation(cache::Dict{…}, src::Core.MethodInstance, cfg::GPUCompiler.CompilerConfig{…}, compiler::Function, linker::Function)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/U36Ed/src/execution.jl:103
 [16] macro expansion
    @ ~/.julia/packages/CUDA/YIj5X/src/compiler/execution.jl:382 [inlined]
 [17] macro expansion
    @ ./lock.jl:267 [inlined]
 [18] cufunction(f::typeof(ClimaCore.DataLayouts.knl_copyto!), tt::Type{Tuple{ClimaCore.DataLayouts.IJFH{…}, Base.Broadcast.Broadcasted{…}}}; kwargs::@Kwargs{})    @ CUDA ~/.julia/packages/CUDA/YIj5X/src/compiler/execution.jl:377
 [19] cufunction(f::typeof(ClimaCore.DataLayouts.knl_copyto!), tt::Type{Tuple{ClimaCore.DataLayouts.IJFH{…}, Base.Broadcast.Broadcasted{…}}})
    @ CUDA ~/.julia/packages/CUDA/YIj5X/src/compiler/execution.jl:374
 [20] macro expansion
    @ ~/.julia/packages/CUDA/YIj5X/src/compiler/execution.jl:104 [inlined]
 [21] copyto!(dest::ClimaCore.DataLayouts.IJFH{…}, bc::Base.Broadcast.Broadcasted{…})
    @ ClimaCore.DataLayouts ~/.julia/packages/ClimaCore/WtnDS/src/DataLayouts/cuda.jl:81
 [22] copy
    @ ./broadcast.jl:928 [inlined]
 [23] materialize
    @ ./broadcast.jl:903 [inlined]
 [24] update_surface_conditions!(Y::ClimaCore.Fields.FieldVector{…}, p::@NamedTuple{…}, t::Float32)
    @ ClimaAtmos.SurfaceConditions ~/ClimaAtmos.jl/src/surface_conditions/surface_conditions.jl:32
 [25] macro expansion
    @ ~/ClimaAtmos.jl/src/cache/precomputed_quantities.jl:345 [inlined]
 [26] set_precomputed_quantities!(Y::ClimaCore.Fields.FieldVector{…}, p::@NamedTuple{…}, t::Float32)
    @ ClimaAtmos ~/.julia/packages/NVTX/bQF8h/src/macro.jl:194
 [27] build_cache(Y::ClimaCore.Fields.FieldVector{…}, atmos::ClimaAtmos.AtmosModel{…}, params::ClimaAtmos.Parameters.ClimaAtmosParameters{…}, surface_setup::ClimaAtmos.SurfaceConditions.DefaultExchangeCoefficients, dt::Float32, t_end::Float32, start_date::Dates.DateTime)
    @ ClimaAtmos ~/ClimaAtmos.jl/src/cache/cache.jl:177
 [28] macro expansion
    @ ~/ClimaAtmos.jl/src/solver/type_getters.jl:786 [inlined]
 [29] macro expansion
    @ ./timing.jl:503 [inlined]
 [30] macro expansion
    @ ~/ClimaAtmos.jl/src/utils/utilities.jl:294 [inlined]
 [31] get_simulation(config::ClimaAtmos.AtmosConfig{Float32, CLIMAParameters.AliasParamDict{…}, Dict{…}, ClimaComms.SingletonCommsContext{…}})
    @ ClimaAtmos ~/ClimaAtmos.jl/src/solver/type_getters.jl:785
 [32] top-level scope
    @ REPL[13]:1
 [33] top-level scope
    @ ~/.julia/packages/CUDA/YIj5X/src/initialization.jl:208
Some type information was truncated. Use `show(err)` to see complete types.
```

The error seems to point out to the `surface_conditions` functions in `SurfaceFluxes`. Further investigation shows that setting `L_MO = 1.f0` in that function leads to a working simulation. However, this should not be taken as to mean that the issue is there. A similar error was reported on the #gpu channel on the julia slack. 

Pending further investigation.

**Comment by Sbozzolo** [comment] 2024-01-08 23:23
I applied the workaround, but updating to 1.10 will require a little bit more work because of https://github.com/pfitzseb/ProfileCanvas.jl/issues/34

**Comment by juliasloan25** [comment] 2024-03-01 00:48
@Sbozzolo can we close this?

**Comment by Sbozzolo** [comment] 2024-03-01 00:52
I mean, we implemented a couple of workarounds to get this to work...

**Comment by charleskawczynski** [comment] 2024-03-01 02:08
@dennisYatunin pointed out that this was due to the kwargs, which has been updated in SurfaceFluxes.

**Closed by charleskawczynski** 2024-03-01 02:08 UTC
Labels: Dependencies :spider_web:, GPU

**Comment by Sbozzolo** [comment] 2024-03-01 02:24
Yes, I identified that it was due to the keyword argument and applied this
workaround:
https://github.com/CliMA/SurfaceFluxes.jl/commit/5057b32bc9b307449da668b36c39cde744e1bb39
that essentially avoids the keyword arguments in the climaatmos runs.

The very same code worked in 1.9 so I would argue that we never really
fixed the problem.

We also had to reduce the sampling frequency for allocations so that
ProfileCanvas would work. If we could remove the workaround and restore the
higher allocation rate, I think that would be good.

**Comment by charleskawczynski** [comment] 2024-03-01 14:13
> Yes, I identified that it was due to the keyword argument and applied this
workaround:

Yes, but Dennis removed the kwargs entirely, which means that this repository no longer fails on Julia 1.10 on GPUs.

> The very same code worked in 1.9 so I would argue that we never really
fixed the problem.

The real issue is unrelated to ClimaAtmos/SurfaceFluxes, it's either an issue with ClimaCore broadcasting, CUDA, GPUCompiler, or Julia itself.

We've had issues with kwargs on gpus in the past (https://github.com/JuliaGPU/KernelAbstractions.jl/issues/114).

What we really need is a reproducer, so that we can boil it down and open an upstream issue.

**Comment by Sbozzolo** [comment] 2024-03-01 15:44
> Yes, but Dennis removed the kwargs entirely, which means that this repository no longer fails on Julia 1.10 on GPUs.

Got it!

@simonbyrne already spent several hours on this and failed to get a meaningful working example. 

The place we left this off was that it has something to do with error handling and code branches being compiled even they should not be. The keyword argument was not the problem in itself, but it tripped the compiler.

It would be nice to report this if we could get a good reproducer, but I don't think it's worth our time.
