### ISSUE TITLE
AMIP roadmap overview

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaAtmos.jl#355] opened 2022-04-27 18:10 UTC
This issue outlines the AMIP roadmap overview for the atmosphere. This will be updated periodically.

Next to each work delegation item is listed a Nearest (unfinished) Key Result (NKR), pointing to the job ID that the work is contributing towards. A Related Issue (RI) is listed next to the NKR that provides more specific information regarding the general task.

If any team member is working on a stepping stone experiment/job, please comment on this issue so that we can add it to the list. We have a finite set of stepping stones, and outlining all of them should not be overwhelming. If a key result is finished, please comment on this issue so that we can check off the list

### Atmos / physics work
 - Radiation [Zhaoyi] (NKR: None for now)
 - Topography [Akshay] (NKR: `held_suarez_topo`) RI: [CA#408](https://github.com/CliMA/ClimaAtmos.jl/issues/408)
 - Moisture [Jia, Anna] (NKR: `equil_baroclinic_wave`, RI: [CA#363](https://github.com/CliMA/ClimaAtmos.jl/pull/363)
 - Surface Fluxes [Jia, Lenka, Ben, Yair] (NKR: `equil_held_suarez`)
 - EDMF [Yair, Charlie] (NKR: `equil_idealized_aqua_allskyrad_edmf`), we may want to add a stepping stone to this
   - Implicit time stepping

### Features/support needed in ClimaCore 
   - spatially-varying boundary conditions [Ben] (NKR: `equil_held_suarez`)
 - stretched grid with correct weights [Simon] (NKR: `held_suarez`)
 - upwinding [Simon] (NKR: `held_suarez`)
 - Spherical limiters [Valeria, Simon] (NKR: `equil_baroclinic_wave`)
 - performance [Sriharsha] (NKR: `held_suarez`)

### Land / Coupler work
 - Coupler [Lenka, Ben]
   - `equil_baroclinic_wave_slab` - add slab ocean with MPI [CC#39](https://github.com/CliMA/ClimaCoupler.jl/issues/39)
   - `sea_breeze_topog` - Cartesian topography + land / ocean mask in building on the rising bubble setup [CC#40](https://github.com/CliMA/ClimaCoupler.jl/issues/40)
   - `equil_baroclinic_wave_bucket` - stub for the full land model  [CC#41](https://github.com/CliMA/ClimaCoupler.jl/issues/41)
   - `equil_baroclinic_wave_bucket_seaice` - sea ice + land /sea mask  [CC#42](https://github.com/CliMA/ClimaCoupler.jl/issues/42)
   - `equil_baroclinic_wave_bucket_seaice_topog`  [CC#43](https://github.com/CliMA/ClimaCoupler.jl/issues/43)
 - Land [Katherine]
   - Implicit time stepping (non-bucket land model)

### List of key results (via buildkite jobs)
```
[completion %] job_id:          configuration flags
[ ✓ ] baroclinic_wave:                          --config SP
[ ✓ ] held_suarez:                              --config SP --HSF true
[0.6] held_suarez_topo:                         --config SP --HSF true --topo true
[ ✓ ] equil_baroclinic_wave:                    --config SP --moist equil --micro 0M
[ ✓ ] equil_held_suarez:                        --config SP --moist equil --HSF true --SF true --VD true --micro 0M
[ ✓ ] equil_idealized_aqua_grayrad:             --config SP --moist equil --SF true --VD true --micro 0M --rad gray
[ ✓ ] equil_idealized_aqua_clearskyrad:         --config SP --moist equil --SF true --VD true --micro 0M --rad clear_sky
[   ] equil_idealized_aqua_clearskyrad_topo:    --config SP --moist equil --SF true --VD true --micro 0M --rad clear_sky --topo true
[   ] equil_idealized_aqua_allskyrad_edmf:      --config SP --moist equil --SF true --rad all_sky --turbconv edmf
[   ] equil_idealized_aqua_allskyrad_edmf_topo: --config SP --moist equil --SF true --rad all_sky --turbconv edmf --topo true
[ ✓ ] radiative_equilibrium_clearsky:           --config SC --DCE false --rad clear_sky
[ ✓ ] radiative_equilibrium_gray:               --config SC --DCE false --rad gray
[ ✓ ] radiative_equilibrium_allsky:             --config SC --DCE false --rad all_sky
[0.6] radiative_convective_equilibrium:         --config SC --DCE false --rad all_sky --turbconv edmf
```

### Physics acronyms
 - DCE = Dynamical core equations
 - topo = Topography
 - GW = Gravity wave
 - turbconv = TurbulenceConvection
 - rad = Radiation (i.e., RRTMGP.jl)
 - 0M = 0-moment microphysics
 - VD = Vertical diffusion
 - HSF = Held Suarez forcing
 - L = Land
 - M = moisture (dry, equil, non-equil)

### Configuration acronyms
 - SP = Spherical configuration - A full 3D spherical configuration, at coarse or fine resolution (determined by cli arguments)
 - SC = Single Column configuraiton - A "single column" configuration where we run a spherical case with 6 faces, 1 element per face, 0-poly order and horizontally decoupled. These configurations with horizontal coupling (i.e., horizontal advection) + higher resolution should yield an effectively 3D spherical case

**Comment by szy21** [comment] 2022-04-29 21:21
For the radiation, it is done but we only added `radiative_equilibrium_allsky` in the buildkite (maybe a better name would be `radiative_equilibrium_clearsky` because there is no cloud). We'll add a regression test to it once we finalize the details (e.g. interpolation). I think Dennis would like to change something in the command line arguments and driver, and we can add `radiative_equilibrium_gray` after that.

I think `held_suarez` would be a better NKR for stretched grid with correct weights. It's better to make sure it works on the sphere configuration. `held_suarez` can also be an NKR for upwinding.

**Comment by bischtob** [comment] 2022-06-03 14:56
@szy21 , can you update the numbers for radiation runs?

**Comment by szy21** [comment] 2023-08-17 06:31
This is a bit outdated, and we have new documents tracking this, so I'm closing the issue.

**Closed by szy21** 2023-08-17 06:31 UTC
