### ISSUE TITLE
Clean up package dependencies

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaAtmos.jl#2100] opened 2023-09-18 15:22 UTC
Linked PR : https://github.com/CliMA/SurfaceFluxes.jl/pull/128
Linked PR : https://github.com/CliMA/SurfaceFluxes.jl/pull/127

**Comment by simonbyrne** [comment] 2023-09-21 16:24
@akshaysridhar can you expand on what the issue is here? Or close it?

**Closed** 2023-09-21 16:24 UTC
